version: '3.4'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
     - 27017:27017

  carcore.api:
    image: ${DOCKER_REGISTRY-}carcoreapi
    build:
      context: .
      dockerfile: Carcore.API/Dockerfile
    ports:
     - 7076:443
    environment:
     - connectionString=mongodb://mongodb:27017