version: '3.4'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017

  backend:
    container_name: carecoreapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7076:80
    depends_on:
      - mongodb
    environment:
      - connectionString=mongodb://mongodb:27017
    #   - ASPNETCORE_URLS=http://+:7076

