version: '3.4'

services:
  frontend:
      build:
        context: .
        dockerfile: Dockerfile-frontend
      restart: always
      ports:
        - 4200:80
      # depends_on:
      #   - backend
