version: '3'
services:
  carcoredb:
    container_name: carcoredb
    image: mongo:latest
    restart: always
    ports:
    - 27017:27017

  carcore.api:
    container_name: catalogapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    depends_on:
      - carcoredb
    environment:
      - connectionString=mongodb://carcoredb:27017
