ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Qualitätsanforderungen

// Funktions- und Unit Tests
Functional Suitability:: 
- Die Anwendung kann Daten in eine externe Datenbank schreiben und die Daten erfolgreich daraus lesen.
// Testcontainers 
- Die Anwendung kann eine API aufrufen und die erwarteten Antworten empfangen. 
// Testcontainers 
- Die Anwendung bietet eine Oberfläche, über die Benutzer mit den Daten interagieren können 


// Lasttests
Performance:: 
- Die erwartete Benutzerlast sind 100 gleichzeitige Benutzeranfragen.
- Die durchschnittliche Antwortzeit der Anwendung bei der definierten Benutzerlast liegt unter 1 Sekunde.
- Die Anwendung ist in der Lage, 150 gleichzeitige Benutzeranfragen pro Sekunde zu verarbeiten, ohne dass die durchschnittliche Antwortzeit auf über 3 Sekunden steigt.


Maintainability::
- Quellcode soll durch den Einsatz der passenden Patterns modular aufgebaut sein
- Das Code Repository wird bei jedem Checkin automatisiert gebaut 
// GitHub Actions 
- Alle Datenzugriffsoperationen erfolgen ausschließlich über die definierte Schnittstelle 
- Alle Schnelllaufenden Tests (Unit Test, ..., halt keine End-to-end tests oder so) werden bei jedem Check-in getestet. 
// GitHub Actions 
- Alle Auffälligkeiten aus der statischen Codeanalyse müssen beseitigt werden (0 Violation Policy) 
// Sonarcloud 
- Das System sollte eine Test Coverage von mindestens 80 % aufweisen.


Sicherheit::
- Die Anwendung soll den Entwickler über veraltete Abhängigkeiten zu NuGet Paketen informieren und diese bei Bedarf direkt aktualisieren. 
// GitHub Dependabot 
- Die Anwendung soll gegen die OWASP Top 10 Application Security Risks geschützt sein 
// OWASP DependencyCheck 
- Es werden ausschließliche sichere Kommunikationsprotokolle verwendet (HTTPS statt HTTP)


Usability::
- Inkonsistente Benutzereingaben sollen erkannt werden 
- Kontrollelemente sollen erst klickbar sein, wenn die Ausführung dieser einen Sinn ergibt. 


Andere Qualitätsanforderungen wie Reliability und Skalierbarkeit wurden als weniger relevant für die Anwendung angesehen.



// .Weiterführende Informationen

// Siehe https://docs.arc42.org/section-10/[Qualitätsanforderungen] in der online-Dokumentation (auf Englisch!).


