
name: OWASP Zap Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
   
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3

      - name: Start API
        run: |
              dotnet restore Carcore/Carcore.sln 
              dotnet build Carcore/Carcore.sln --no-incremental
              dotnet run --project Carcore/Carcore.API/Carcore.API.csproj &

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: 'http://localhost:7076/swagger/v1/swagger.json'
          format: openapi
          docker_name: owasp/zap2docker-stable
          allow_issue_writing: false