
name: OWASP Zap Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Start API
        run: |
              dotnet restore app/Carcore/Carcore.sln 
              dotnet build app/Carcore/Carcore.sln --no-incremental
              dotnet run --project app/Carcore/Carcore.csproj &

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: 'http://localhost:7076/swagger/v1/swagger.json'
